In [5]:
import pandas as pd
df=pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
# 그룹핑 grouby.size,mean,max,min,count ...

# 그룹화 - 통계, 평균
# 학교가 -구로고, 디지털고 인 행만 출력가능
# df.groupby('학교').get_group('구로고')
# df.groupby('학교').get_group('디지털고')

# 중복제외 학교의 값을 알수있음
df['학교'].unique()
# 학교기준으로 그룹핑을 해서 크기 확인 가능
df.groupby('학교').size()
# 학교 기준으로 구로고, 디저털고의 개수를 알 수 있음
df.groupby('학교').size()['구로고'] 
df.groupby('학교').size()['디지털고'] 

# 학교 기준으로 키의 평균을 알 수 있음
df.groupby('학교')['키'].mean()
# 학교 기준으로 국어의 평균을 알 수 있음
df.groupby('학교')['국어'].mean()
# 학교 기준으로 국어,수학의 평균을 알 수 있음
df.groupby('학교')[['국어','수학']].mean()
# 학교 기준으로 국어,수학의 합계을 알 수 있음
df.groupby('학교')[['국어','수학']].sum()

       국어   수학
학교
구로고   265  300
디지털고  235  230

In [6]:
df['학년']=[3,3,2,1,1,3,2,2]
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기  학년
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python   3
2번    강태원   구로고  184   40   35   50  55  25        Java   3
3번    강호림   구로고  168   80   75   70  80  75  Javascript   2
4번    김수찬   구로고  187   40   60   70  75  80         NaN   1
5번    김재욱   구로고  188   15   20   10  35  10         NaN   1
6번    박동현  디지털고  202   80  100   95  85  80           C   3
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON   2
8번    승근열  디지털고  190  100   85   90  95  95          C#   2

In [ ]:
# 그룹핑을 한 후 개수 확인 / 같은 말
# df.groupby('학교').size()
# value_counts()가 자동으로 개수가 많은 순서로 정렬
df['학교'].value_counts()

학교
구로고     5
디지털고    3
Name: count, dtype: int64

In [10]:
# 학교로 그룹핑 한 다음, 학년을 기준으로 나눌 수 있다
# df.groupby('학교')['학년'].value_counts()

# 학교로 그룹핑 한 다음, 학년을 기준으로 나눔->구로고 것만 알 수 있음
# df.groupby('학교')['학년'].value_counts().loc['구로고']
# 학교로 그룹핑 한 다음, 학년을 기준으로 나눔->디지털고 것만 알 수 있음
# df.groupby('학교')['학년'].value_counts().loc['디지털고']

# normalize 백분율로 표시 :원형 그래프
df.groupby('학교')['학년'].value_counts(normalize=True).loc['구로고']

학년
3    0.4
1    0.4
2    0.2
Name: proportion, dtype: float64

In [ ]:
# 학년 별 키의 평균->정렬
df.groupby('학년')['키'].mean().sort_values()

# 학년 별 국어, 영어의 합->국어를 기준으로 정렬하라
df.groupby('학년')[['국어','영어']].sum().sort_values('국어')
# 학교 별 국어, 영어의 평균->영어 기준으로 정렬하라
df.groupby('학교')[['국어','영어']].mean().sort_values('영어')

             국어         영어
학교
구로고   53.000000  55.000000
디지털고  78.333333  83.333333

In [22]:
import pandas as pd
df=pd.read_csv('file/drinks.csv')
# 컬럼 continent의 값 중 각 각 중복이 몇개인지 알 수 있음
df.groupby('continent').size().sort_values(ascending=False)

continent
AF    53
EU    45
AS    44
OC    16
SA    12
dtype: int64

In [ ]:
import pandas as pd
df=pd.read_csv('file/drinks.csv')
# continent 대륙별 퍼센트를 출력하시오.

# df.groupby('continent').size().value_counts(normalize=True)

(df['continent'].value_counts(normalize=True)*100)

continent
AF    31.176471
EU    26.470588
AS    25.882353
OC     9.411765
SA     7.058824
Name: proportion, dtype: float64