In [1]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus']=False    # -가 안깨지도록(- 부호 처리)
matplotlib.rcParams['font.family']='Malgun Gothic'  #한글처리: 윈도우 맑은 고딕 저장
matplotlib.rcParams['font.size']=15                 #전체 글자폰트크기 조정
# matplotlib.rcParams['font.family']='AppleGithic'    #맥컴 애플고딕 저장

import pandas as pd
import numpy as np #NumPy는 숫자 계산용

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
import requests
from bs4 import BeautifulSoup
import time
import os
from dotenv import load_dotenv

In [3]:
df=pd.read_csv('file/namu1.csv')
df.head(3)

   Unnamed: 0     title                                                url
0           0     조지 웨아  https://namu.wiki/w/%EC%A1%B0%EC%A7%80%20%EC%9...
1           1        경지             https://namu.wiki/w/%EA%B2%BD%EC%A7%80
2           2  군산 버스 19  https://namu.wiki/w/%EA%B5%B0%EC%82%B0%20%EB%B...

In [10]:
# df['url']

In [ ]:
# for url in df['url']:
#     print(url)

In [5]:
url = 'https://namu.wiki/w/%EC%A1%B0%EC%A7%80%20%EC%9B%A8%EC%95%84'
res = requests.get(url)
soup = BeautifulSoup(res.text,'lxml')
title = soup.find('a',{'class':'J23-5aq4'}).get_text(strip=True)
category = soup.find('ul',{'class':'EVpyuXop'}).get_text(strip=True)
content = soup.find('div',{'class':'_6YZgjHNT Oud4u5fe'}).get_text(strip=True)

In [4]:
data = [] 
for url in df['url'].head(50):
    # 2. selenium : 자동화 도구 - 스크롤없이 가져옴
    namu_url = url
    options = Options()
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option("useAutomationExtension", False)
    options.add_argument("--disable-blink-features=AutomationControlled")
    browser = webdriver.Chrome(options=options)
    browser.maximize_window() # 화면 최대창 확대
    browser.get(namu_url)
    time.sleep(2)
    res = requests.get(url)
    time.sleep(1)
    soup = BeautifulSoup(res.text,'lxml')
    title_tag = soup.find('a',{'class':'J23-5aq4'})
    title = title_tag.get_text(strip=True) if title_tag else None
    category_tag = soup.find('ul',{'class':'EVpyuXop'})
    category = category_tag.get_text(strip=True) if category_tag else None
    content_tag = soup.find('div',{'class':'_6YZgjHNT Oud4u5fe'})
    content = content_tag.get_text(strip=True) if content_tag else None
    data.append({
        'title':title,
        'category':category,
        'content':content
    })

print('완료')


# # # 파일저장
# soup = BeautifulSoup(browser.page_source,'lxml')
# with open('file/namu_con1.html','w',encoding='utf-8') as f:
#     f.write(soup.prettify())

완료

In [5]:
n_df=pd.DataFrame(data)
n_df.to_csv('file/namu2.csv')
n_df

,title,category,content
0,조지 웨아,1966년 출생1981년 데뷔2003년 은퇴2018년 은퇴라이베리아 대통령라이베리아...,라이베리아 공화국 대통령[ 펼치기 · 접기 ]초대제2대제3대제4대조셉 젠킨스 로버츠...
1,경지,경지나무위키 웹소설 프로젝트무공칭호(무협),경계선 지능의 줄임말에 대한 내용은경계선 지능문서를 참고하십시오.보드게임 '벚꽃 내...
2,군산 버스 19,군산시의 시내버스,군산시시내버스 노선[ 펼치기 · 접기 ]미성동010203070809옥구읍111213...
3,House 2,2026년 Windows 게임미국 게임액션 어드벤처 게임호러 게임,하우스 2House 2개발Bark Bark Games유통Glowstick Enter...
4,장갑기병 보톰즈 회색의 마녀,보톰즈 시리즈일본 애니메이션/목록2026년 애니메이션 영화2026년 4분기 일본 애...,로도스도 전기에 등장하는 '회색의 마녀'에 대한 내용은칼라(포세리아)문서를 참고하십...
5,카드 앙 시엘/카드/드로,인티 크리에이츠카드 앙 시엘카드 앙 시엘/카드,카드 앙 시엘 카드 목록0코스트3코스트드로디버그리부트무브메모리 리크변신브레이크 포인...
6,사용자:SamSara,NaN,NaN
7,제단(워크래프트 3),워크래프트 3/건물,1. 개요2. 시스템3. 종류4. 여담Altar1.개요[편집]워크래프트 3의 종족 ...
8,빅 미키,토마스와 친구들/등장인물TUGS/등장인물1989년 창조된 캐릭터,크레인들[ 펼치기 · 접기 ]노스 웨스턴 철도 소속크랭키칼리빅 미키레지테스협궤 철도...
9,제임스 로니,1984년 출생2006년 데뷔2019년 은퇴미국의 야구 선수휴스턴 출신 인물외국인 ...,제임스 로니 관련 틀[ 펼치기 · 접기 ]로스앤젤레스 다저스역대 1라운드 지명선수[...
10,제25보병사단 DMZ 지뢰 폭발 사건,이재명 정부/사건사고/2026년대한민국 육군/사건 사고지뢰제25보병사단김정은 시대연...,한시적 넘겨주기로 연결되는 다른 문서에 대한 내용은 아래 문서를 참고하십시오.9월 ...
11,탱킹,스포츠 용어,MMORPG에서의 탱킹에 대한 내용은탱커문서를 참고하십시오.1. 개요2. 의도 및 ...
12,와다,성씨/일본,1. 개요2. 실존 인물3. 가상 인물1.개요[편집]わだ2015년 기준 和田는 42...
13,NaN,NaN,NaN
14,NaN,NaN,NaN
15,명탐정 코난: 시한장치의 마천루,명탐정 코난(애니메이션)/극장판일본 애니메이션/목록1997년 애니메이션 영화1997...,극장판[ 펼치기 · 접기 ]1기2기3기4기5기시한장치의 마천루(줄거리/쿠키 영상)1...
16,제단(워크래프트 3),워크래프트 3/건물,1. 개요2. 시스템3. 종류4. 여담Altar1.개요[편집]워크래프트 3의 종족 ...
17,영천시/정치,영천시경상북도의 정치,상위 문서:영천시관련 문서:영천시·청도군경상북도정치[ 펼치기 · 접기 ]경산시경주시...
18,극장판 이나즈마 일레븐 최강군단 오우거의 습격,이나즈마 일레븐 시리즈/애니메이션일본 애니메이션/목록2010년 애니메이션 영화일본의...,[ 펼치기 · 접기 ]무인 시리즈(애니메이션)이나즈마 일레븐이나즈마 일레븐 RE이나...
19,NaN,NaN,NaN
20,1991년 이라크 봉기,아시아의 봉기1991년 정치바트주의 이라크의 전쟁 및 전투사담 후세인이란-이라크 관...,1991년 이라크 봉기1991 Iraqi uprisings반군에 의해 파괴된 이라크...
21,2003 쇼트트랙 스피드 스케이팅 유럽선수권 대회,쇼트트랙 스피드 스케이팅 유럽선수권 대회,←2001-02ISU 쇼트트랙 스피드 스케이팅 2002-03 시즌2003-04→[ ...
22,불꽃 파이터즈/역대 전적/2026 시즌/경기 목록,불꽃야구2026년 야구2026년 방송 프로그램,상위 문서:불꽃 파이터즈/역대 전적/2026 시즌1. 개요1.1. 시즌 포맷 변경점...
23,흑색왜성,왜성(천체)가설상의 천체,편집 보호된 문서입니다. 문서의ACL 탭을 확인하세요.항성의진화[ 펼치기 · 접기 ...
24,NaN,NaN,NaN
25,김환희/골 때리는 그녀들/클럽 경력,FC 액셔니스타/현역,상위 문서:김환희/골 때리는 그녀들1. 개요2. 클럽2.1.FC 액셔니스타1.개요[...
26,NaN,NaN,NaN
27,사용자:Hexy_Joe/빠른 이동 및 연습장,NaN,NaN
28,난칸마치,구마모토현의 정1957년 설치된 행정구역,구마모토현시정촌[ 펼치기 · 접기 ]정령지정도시현청정령구마모토시(▶ 하위 행정구역)...
29,NaN,NaN,NaN
30,손무,몰년 미상춘추전국시대 및 진나라(영성)의 철학자둥잉시 출신 인물군사학자,손자(인물)은(는) 여기로 연결됩니다. 제(齊)나라의 손자(孫子)에 대한 내용은손빈...
31,FSO 폴로네즈,FSO/생산차량1978년 출시된 자동차2002년 단종된 자동차중형 해치백중형 왜건그룹 4,Polonez[1]1. 개요2. 배경 및 개발3. 출시 및 생산3.1. 폴로네즈(1...
32,2002 쇼트트랙 스피드 스케이팅 유럽선수권 대회,쇼트트랙 스피드 스케이팅 유럽선수권 대회,←2000-01ISU 쇼트트랙 스피드 스케이팅 2001-02 시즌2002-03→[ ...
33,PC정비사,컴퓨터정보통신자격면허,(사)한국정보평가협회(KIE)가 운영하는 국가공인민간자격증에 대한 내용은PC Mas...
34,불꽃 파이터즈/역대 전적/2026 시즌/경기 목록,불꽃야구2026년 야구2026년 방송 프로그램,상위 문서:불꽃 파이터즈/역대 전적/2026 시즌1. 개요1.1. 시즌 포맷 변경점...
35,분류:바트주의 이라크의 전쟁 및 전투,바트주의 이라크이라크의 전쟁 및 전투,
36,김환희/골 때리는 그녀들/클럽 경력/FC 액셔니스타,FC 액셔니스타/현역,상위 문서:김환희/골 때리는 그녀들/클럽 경력김환희시즌 8-소속 팀FC 액셔니스타소...
37,안양 정관장 레드부스터스,안양 정관장 레드부스터스한국인삼공사안양시 연고 구단대한민국의 프로 농구단한국프로농구...,2026-27 시즌에 대한 내용은안양 정관장 레드부스터스/2026-27 시즌문서를 ...
38,잔스파인/SD건담 지 제네레이션 이터널/UR,SD건담 지 제네레이션 이터널/유닛G제네레이션 시리즈/오리지널 기체베스파의 모빌슈트,"다른 지 제네레이션 시리즈에서의 잔스파인에 대한 내용은잔스파인문서를, 원작의 파라 ..."
39,사용자:SamSara,NaN,NaN
40,부산 OK저축은행 읏맨,부산 OK저축은행 읏맨OK금융그룹부산광역시 연고 구단연고지 이전대한민국의 프로 배구...,2026-27 시즌에 대한 내용은부산 OK저축은행 읏맨/2026-27 시즌문서를 참...
41,NaN,NaN,NaN
42,NaN,NaN,NaN
43,토오사카 린/작중 행적/본편,Fate 시리즈/캐릭터/작중 행적토오사카 린,상위 문서:토오사카 린/작중 행적이 문서에스포일러가 포함되어 있습니다.이 문서가 설...
44,김주성(야구선수)/선수 경력,대한민국의 야구 선수/경력,상위 문서:김주성(야구선수)1. 개요2. 아마추어 시절3.LG 트윈스3.1. 201...
45,리그 오브 레전드/증강/프리즘,리그 오브 레전드/증강,상위 문서:리그 오브 레전드/증강리그 오브 레전드의증강실버골드프리즘1. 개요2. 공...
46,조지 웨아,1966년 출생1981년 데뷔2003년 은퇴2018년 은퇴라이베리아 대통령라이베리아...,라이베리아 공화국 대통령[ 펼치기 · 접기 ]초대제2대제3대제4대조셉 젠킨스 로버츠...
47,사용자:Wpdl,NaN,NaN
48,아스파르,고트족동음이의어동로마 제국의 군인동로마의 섭정400년 출생471년 사망고대 로마의 ...,프린세스 메이커 5의 인물에 대한 내용은아스파르(프린세스 메이커 5)문서를 참고하십...
49,2025년/사건,2025년/사건사고,상위 문서:2025년연도별 사건 문서 바로가기2025년 사건←2024년 사건2026...